workflows:
  android-debug:
    name: Android Debug Build
    max_build_duration: 60
    environment:
      vars:
        JAVA_HOME: /usr/lib/jvm/adoptopenjdk-17-hotspot-amd64
    scripts:
      - name: Fix gradlew permission
        script: chmod +x ./gradlew
      - name: Install Android SDK 34 build tools
        script: |
          sdkmanager "platforms;android-34" "build-tools;34.0.0"
      - name: Clean project and refresh dependencies
        script: ./gradlew clean --no-daemon --refresh-dependencies
      - name: Assemble debug APK
        script: ./gradlew assembleDebug --no-daemon
    artifacts:
      - app/build/outputs/**/*.apk
