workflows:
  android-build:
    name: Android Debug & Release Build
    max_build_duration: 60
    scripts:
      - name: Fix gradlew permission
        script: chmod +x ./gradlew

      # On supprime l'installation SDK via script, Codemagic gère SDK/Build Tools via UI

      - name: Clean project and refresh dependencies
        script: ./gradlew clean --no-daemon --refresh-dependencies

      - name: Assemble debug APK
        script: ./gradlew assembleDebug --no-daemon --stacktrace

      - name: Assemble release APK
        script: ./gradlew assembleRelease --no-daemon --stacktrace

    artifacts:
      - app/build/outputs/**/*.apk

caches:
  paths:
    - ~/.gradle/caches
    - ~/.gradle/wrapper/
    - app/build/generated/ksp
