workflows:
  android-build:
    name: Android Debug & Release Build
    max_build_duration: 60
    scripts:
      # Fix gradlew permissions
      - name: Fix gradlew permission
        script: chmod +x ./gradlew

      # Installer SDK 34 et build-tools 34
      - name: Install Android SDK 34 build tools
        script: |
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-34" "build-tools;34.0.0"

      # Clean et refresh dependencies pour KSP
      - name: Clean project and refresh dependencies
        script: ./gradlew clean --no-daemon --refresh-dependencies

      # Build Debug APK
      - name: Assemble debug APK
        script: ./gradlew assembleDebug --no-daemon --stacktrace

      # Build Release APK
      - name: Assemble release APK
        script: ./gradlew assembleRelease --no-daemon --stacktrace

    artifacts:
      - app/build/outputs/**/*.apk

caches:
  paths:
    - ~/.gradle/caches
    - ~/.gradle/wrapper/
    - app/build/generated/ksp
